# fish
brew "bat"
brew "direnv"
brew "exa"
brew "fish"
brew "starship"

# git
brew "git-delta"
brew "patchutils"

# helix
brew "helix"

# utils
brew "coreutils"
brew "gnu-sed"
brew "grep"
brew "htop"
brew "jq"
brew "ncdu"
